# Site settings
title: "Portfolio NM"
description: "Applying institutional risk management principles to DeFi portfolios and CLMM market making."

# Paramètres d'URL
url: "https://nicomace.github.io"
baseurl: "/testDeFi"

# Thème
remote_theme: just-the-docs/just-the-docs

# Fix pour le Menu : Forcer Jekyll à inclure tes dossiers de contenu
# Si tes fichiers sont dans "_pages", on dit à Jekyll de ne pas les ignorer
include:
  - _pages
  - project 

# Configuration de la navigation
nav_enabled: true
#nav_external_links:
  #- title: "GitHub Repo"
  #  url: https://github.com/nicomace/testDeFi

# Recherche
search_enabled: false

# Look & Feel
color_scheme: dark 

# Build settings
markdown: kramdown
# Attention : Just the Docs préfère souvent les permaliens simples
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Pied de page
footer_content: "Copyright &copy; 2026 Nicolas Macé."

# Liens rapides en haut de la sidebar
aux_links:
  "Linkedin": "https://www.linkedin.com/in/macenicolas/"
  "X": "https://x.com/niclos96"
  "GitHub": "https://github.com/nicomace/testDeFi"

# Paramètres par défaut
defaults:
  - scope:
      path: ""
    values:
      layout: default

sass:
  style: compressed
  
# Just the Docs settings
just_the_docs:
  # Permet d'injecter des composants personnalisés
  collections:
    setup:
      nav_exclude: true
      
  typekit_id: 
  search_enabled: false
    # On s'assure que le footer n'affiche que votre texte
  last_edit_enabled: false
