# Site settings
title: NicoMace Portfolio
description: "Applying institutional risk management principles to DeFi portfolios and CLMM market making."

# Paramètres d'URL
url: "https://nicomace.github.io"
baseurl: "/testDeFi"

# Thème
remote_theme: just-the-docs/just-the-docs

# Fix pour le Menu : Forcer Jekyll à inclure tes dossiers de contenu
# Si tes fichiers sont dans "_pages", on dit à Jekyll de ne pas les ignorer
include:
  - _pages
  - project 

# Configuration de la navigation
nav_enabled: true
nav_external_links:
  - title: "GitHub Repo"
    url: https://github.com/nicomace/testDeFi

# Recherche
search_enabled: true

# Look & Feel
color_scheme: dark 

# Build settings
markdown: kramdown
# Attention : Just the Docs préfère souvent les permaliens simples
permalink: pretty

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Pied de page
footer_content: "Copyright &copy; 2026 Nicolas Macé. Built with Just the Docs."

# Liens rapides en haut de la sidebar
aux_links:
  "Linkedin": "https://www.linkedin.com/in/macenicolas/"
  "GitHub": "https://github.com/nicomace"

# Paramètres par défaut
defaults:
  - scope:
      path: ""
    values:
      layout: default
